export const INITIALIZED = 'INITIALIZED';
export const ROOT_CHANGED = 'ROOT_CHANGED';
export const CONFIRM_PASSWORD_ERROR = 'CONFIRM_PASSWORD_ERROR';
export const QUESTION_FETCHED = 'QUESTION_FETCHED';
export const ANSWER_SELECTED = 'ANSWER_SELECTED';
export const COMMENT_CHANGE = 'COMMENT_CHANGE';
export const NEXT_ANSWER = 'NEXT_ANSWER';
